services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    #environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    networks:
      external:
          ipv4_address: 192.168.23.100
      default:

    volumes:
      - data:/data
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/cloudflare.ini:/etc/cloudflare.ini

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nvme/nginx/data

networks:
  default:
    name: aquinet
    external: true
  external:
    name: external
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: "192.168.22.0/23"
          gateway: "192.168.22.1"
    driver_opts:
      parent: enp1s0
  immich_default:
    name: immich_default
    external: true
