---
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j:/logs
      - neo4j:/config
      - neo4j:/data
      - neo4j:/plugins
    environment:
      - NEO4J_dbms_security_auth__minimum__password__length=6
      - NEO4J_AUTH=neo4j/lwrbsd
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
volumes:
  neo4j: