services:
  dumbassets:
    container_name: dumbassets
    image: dumbwareio/dumbassets:latest
    restart: unless-stopped
    ports: 
      - 3002:3000
    volumes:
      - ${DUMBASSETS_DATA_PATH:-./data}:/app/data
    environment:
      NODE_ENV: production
      DEBUG: true
      SITE_TITLE: DumbAssets
      BASE_URL: https://da.aquino.network
      DUMBASSETS_PIN: 8307
      ALLOWED_ORIGINS: '*'
      CURRENCY_CODE: ${DUMBASSETS_CURRENCY_CODE:-BRL}
      CURRENCY_LOCALE: ${DUMBASSETS_CURRENCY_LOCALE:-pt-BR}
      TZ: America/Sao_Paulo

networks:
  default:
    name: aquinet
    external: true
