services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      default:
          ipv4_address: 192.168.23.102
    volumes:
      - /mnt/nvme/forgejo:/forgejo
      - /mnt/nvme/forgejo/conf/app.ini:/etc/forgejo/app.ini:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
networks:
  default:
    name: external
    external: true
